// SPDX-License-Identifier: Apache-2.0

// Mirrors the bindings declared in wrangler.jsonc (SPEC §5). Update both together.
//
// Most bindings are declared but not consumed in M0 — the typed shape exists so
// later milestones can import a stable Env without churn.

import type {
  AnalyticsEngineDataset,
  D1Database,
  DurableObjectNamespace,
  KVNamespace,
  R2Bucket,
} from "@cloudflare/workers-types";
import type { AiSearchBinding, WorkersAiBinding } from "./ai-search-binding.js";
import type { ArtifactsBinding } from "./artifacts-binding.js";

export interface VersionMetadata {
  id: string;
  tag: string;
  timestamp: string;
}

export interface Env {
  // Durable Objects
  CHAT_ROOM: DurableObjectNamespace;

  // Storage
  DB: D1Database;
  ATTACHMENTS: R2Bucket;
  CACHE: KVNamespace;

  // Wiki content (M4). KV-backed for v0.0.1; M4.5 swaps this for
  // git-over-HTTPS against the Artifacts repo. See docs/ADR/0003.
  WIKI_KV: KVNamespace;

  // Cloudflare Artifacts binding. The runtime type `Artifacts` is
  // generated by `pnpm wrangler types` into worker-configuration.d.ts.
  // Exposes repo lifecycle only — `create`, `get`, `list`, `delete`,
  // `import` plus token mgmt on the repo handle (createToken, listTokens,
  // revokeToken, fork). There is no file-level read/write on the
  // binding; that's the standard git protocol against repo.remote, which
  // M4.5 will implement. See lib/artifacts.ts for the typed wrapper.
  // Optional because the Artifacts beta is allowlist-gated. Operators
  // not on the allowlist comment out the `artifacts` binding in
  // wrangler.jsonc; the v0.0.1 wiki content path uses WIKI_KV (M4
  // backend) and never reads env.ARTIFACTS, so the deploy works
  // without it. The two admin routes that DO call into it
  // (`/api/_admin/wiki/bootstrap-vault`, `/api/_admin/wiki/vault-token`)
  // throw a clear LoomwikiError when the binding is missing — they
  // are M4.5 plumbing, not part of the dogfood happy path.
  ARTIFACTS?: ArtifactsBinding;

  // AI
  AI: WorkersAiBinding;

  // M6: AI Search hybrid (BM25 + vector) over the workspace vault.
  // Optional at the type level because local dev configs (and operator
  // accounts without AI Search) won't have it; the search orchestrator
  // catches the binding-missing case and falls through to FTS5.
  AI_SEARCH?: AiSearchBinding;

  // Version metadata (populated by CF in production deploys; may be undefined in dev)
  CF_VERSION_METADATA?: VersionMetadata;

  // Analytics (placeholder for M8)
  ANALYTICS?: AnalyticsEngineDataset;

  // Vars
  WORKSPACE_NAME: string;
  DEFAULT_LLM_MODEL: string;
  EMBEDDING_MODEL: string;
  ARTIFACTS_REPO: string;
  AI_SEARCH_INSTANCE: string;
  GIT_COMMIT?: string;

  // Cloudflare Access — operator must override these in production via the
  // dashboard or a wrangler env section. Defaults in wrangler.jsonc are dev
  // placeholders that tests exercise via mocked JWKS in KV.
  ACCESS_TEAM: string;
  ACCESS_AUD: string;

  // Local-dev auth bypass. Triple-gated; see middleware/auth.ts. Default off.
  ALLOW_LOCAL_DEV_AUTH: string;
  LOCAL_DEV_EMAIL: string;

  // M6: AI Search + cost guards. Strings (not numbers/booleans) because
  // wrangler vars are always strings; lib/llm.ts and lib/cost-guard.ts
  // parse them at use time.
  AI_SEARCH_ENABLED: string;
  AI_GATEWAY_ID: string;
  CF_ACCOUNT_ID: string;
  LLM_DAILY_LIMIT_PER_USER_ASK: string;
  LLM_DAILY_LIMIT_PER_USER_SEARCH: string;
  LLM_DAILY_LIMIT_PER_WORKSPACE_ASK: string;
  LLM_DAILY_LIMIT_PER_WORKSPACE_SEARCH: string;
  // M7: ingest cost guard. Workspace-scoped only — manual triggers
  // come from members but the run is a shared workspace operation.
  // Default 100/day; tune via wrangler vars.
  INGEST_DAILY_LIMIT_PER_WORKSPACE?: string;

  // M8: deploy-time default for the workspace_settings.timezone column
  // when a workspace hasn't customized it via /settings/workspace yet.
  // Optional — falls back to "UTC" in lib/workspace-settings.ts.
  WORKSPACE_DEFAULT_TIMEZONE?: string;

  // Secrets — undefined locally unless set via .dev.vars
  SENTRY_DSN?: string;
  BYOK_ENCRYPTION_KEY?: string;
  ARTIFACTS_TOKEN?: string;
  AI_GATEWAY_TOKEN?: string;
}
