// SPDX-License-Identifier: Apache-2.0

// Envelope encryption for BYOK keys (M8 / SPEC §22 / ADR-0006).
//
// Master key — `BYOK_ENCRYPTION_KEY` — is a Worker secret, 32 bytes
// base64-encoded (`openssl rand -base64 32`). Per-key fresh 12-byte IV
// generated by crypto.getRandomValues. AES-GCM-256 authenticates so a
// tampered ciphertext or wrong-IV decrypt throws on the auth tag.
//
// The plaintext key only ever exists in memory inside lib/llm.ts for
// the duration of one HTTP request. Never logged, never returned by
// any /api endpoint. lib/byok.ts ensures this contract.

import { ErrorCodes, LoomwikiError } from "@loomwiki/shared";

const ALG = "AES-GCM";
const KEY_BITS = 256;
const KEY_BYTES = KEY_BITS / 8; // 32
const IV_BYTES = 12;

/**
 * Encrypts `plaintext` under the master key. Returns a fresh ciphertext
 * + IV pair. Each call produces a different ciphertext for the same
 * input (IV is freshly random) — that's by design: GCM IV reuse with
 * the same key destroys confidentiality.
 */
export async function encryptValue(
  plaintext: string,
  masterKeyB64: string,
): Promise<{ ciphertext: Uint8Array; iv: Uint8Array }> {
  const key = await importMasterKey(masterKeyB64);
  const iv = crypto.getRandomValues(new Uint8Array(IV_BYTES));
  const data = new TextEncoder().encode(plaintext);
  const cipherBuf = await crypto.subtle.encrypt({ name: ALG, iv }, key, data);
  return { ciphertext: new Uint8Array(cipherBuf), iv };
}

/**
 * Decrypts a `(ciphertext, iv)` pair under the master key. AES-GCM
 * verifies the auth tag during decrypt — a wrong key, wrong IV, or
 * tampered ciphertext all manifest as a decrypt failure (DOMException
 * `OperationError` in the Workers runtime), which we map to a typed
 * `LoomwikiError("BYOK_DECRYPT_FAILED")` so callers can distinguish
 * "no key" (returns null) from "key present but unrecoverable".
 */
export async function decryptValue(
  ciphertext: Uint8Array,
  iv: Uint8Array,
  masterKeyB64: string,
): Promise<string> {
  if (iv.byteLength !== IV_BYTES) {
    throw new LoomwikiError("BYOK_DECRYPT_FAILED", "IV is not 12 bytes", { status: 500 });
  }
  const key = await importMasterKey(masterKeyB64);
  let plainBuf: ArrayBuffer;
  try {
    plainBuf = await crypto.subtle.decrypt({ name: ALG, iv }, key, ciphertext);
  } catch (cause) {
    throw new LoomwikiError("BYOK_DECRYPT_FAILED", "Could not decrypt BYOK key", {
      status: 500,
      details: cause instanceof Error ? cause.name : String(cause),
    });
  }
  return new TextDecoder().decode(plainBuf);
}

/**
 * Internal: parse the base64 master key and import as a CryptoKey for
 * AES-GCM. Cached per-input via a lazy Promise map so repeated calls in
 * the same request don't pay the import cost twice. The cache keys on
 * the base64 string (the secret never changes within a request, and
 * across requests the import is cheap relative to the network hop
 * that's about to happen).
 */
const KEY_CACHE = new Map<string, Promise<CryptoKey>>();

async function importMasterKey(masterKeyB64: string): Promise<CryptoKey> {
  if (typeof masterKeyB64 !== "string" || masterKeyB64.length === 0) {
    throw new LoomwikiError(
      ErrorCodes.INTERNAL_ERROR,
      "BYOK_ENCRYPTION_KEY is not configured. Set via `wrangler secret put BYOK_ENCRYPTION_KEY`.",
      { status: 500 },
    );
  }
  let cached = KEY_CACHE.get(masterKeyB64);
  if (cached) return cached;

  cached = (async () => {
    const raw = base64ToBytes(masterKeyB64);
    if (raw.byteLength !== KEY_BYTES) {
      throw new LoomwikiError(
        ErrorCodes.INTERNAL_ERROR,
        `BYOK_ENCRYPTION_KEY must decode to ${KEY_BYTES} bytes, got ${raw.byteLength}`,
        { status: 500 },
      );
    }
    return crypto.subtle.importKey("raw", raw, { name: ALG, length: KEY_BITS }, false, [
      "encrypt",
      "decrypt",
    ]);
  })();
  KEY_CACHE.set(masterKeyB64, cached);
  return cached;
}

function base64ToBytes(b64: string): Uint8Array {
  // atob is available in Workers; use it rather than node:Buffer so the
  // function works identically in the test pool.
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

/**
 * Sentinel ciphertext used to mark a soft-deleted BYOK row. The real
 * row never produces a 1-byte 0x00 ciphertext (AES-GCM tag alone is 16
 * bytes), so this is unambiguous. lib/byok.ts writes this on delete and
 * checks for it on read.
 */
export const BYOK_DELETED_CIPHERTEXT: Uint8Array = new Uint8Array([0x00]);
export const BYOK_DELETED_IV: Uint8Array = new Uint8Array(0);

export function isDeletedCiphertext(ciphertext: Uint8Array): boolean {
  return ciphertext.byteLength === 1 && ciphertext[0] === 0x00;
}

/**
 * Test helper — generate a fresh random master key in the same shape
 * the operator generates with `openssl rand -base64 32`. Tests use this
 * to produce ephemeral keys per-test rather than reusing a fixture
 * (that mirrors the production constraint that BYOK_ENCRYPTION_KEY is
 * the secret root of the envelope and must not be hard-coded anywhere).
 */
export function generateTestMasterKeyB64(): string {
  const raw = crypto.getRandomValues(new Uint8Array(KEY_BYTES));
  let bin = "";
  for (const b of raw) bin += String.fromCharCode(b);
  return btoa(bin);
}
