// SPDX-License-Identifier: Apache-2.0

// Build-time script: walks vault-template/ and emits a TS module the
// worker can import (Worker code can't read the local filesystem at
// runtime). The output is checked into git so reviewers see what the
// bootstrap routine seeds and CI doesn't need to special-case the
// build step.
//
// Usage:
//   pnpm tsx scripts/precompute-vault-template.ts
//
// Run automatically by the @loomwiki/worker prebuild hook. Re-run by
// hand when vault-template/ changes.

import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, posix, relative } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, "..");
const TEMPLATE_DIR = join(REPO_ROOT, "vault-template");
const OUT_PATH = join(REPO_ROOT, "apps/worker/src/generated/vault-template-manifest.ts");

interface ManifestFile {
  /** POSIX-style path inside the vault, with a leading slash. */
  path: string;
  content: string;
}

function walkMarkdownFiles(root: string): ManifestFile[] {
  const out: ManifestFile[] = [];
  const stack: string[] = [root];
  while (stack.length > 0) {
    const dir = stack.pop();
    if (dir === undefined) continue;
    for (const name of readdirSync(dir).sort()) {
      const full = join(dir, name);
      const st = statSync(full);
      if (st.isDirectory()) {
        stack.push(full);
        continue;
      }
      if (!st.isFile()) continue;
      if (!name.endsWith(".md")) continue;
      const rel = `/${posix.normalize(relative(root, full).split(/\\|\//).join("/"))}`;
      out.push({ path: rel, content: readFileSync(full, "utf8") });
    }
  }
  // Stable ordering: alphabetical by path so re-running produces an
  // identical file (and CI diff is meaningful).
  out.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  return out;
}

function emit(files: ManifestFile[]): string {
  const header = `// SPDX-License-Identifier: Apache-2.0
// AUTO-GENERATED by scripts/precompute-vault-template.ts. Do not edit.
// Regenerate with: pnpm tsx scripts/precompute-vault-template.ts
//
// This module bundles the contents of vault-template/ as a typed array
// so the worker (which has no filesystem at runtime) can seed a fresh
// vault deterministically.

export interface VaultTemplateFile {
  /** POSIX-style path with leading slash, e.g. "/AGENTS.md" or "/wiki/_index.md". */
  path: string;
  content: string;
}

export const VAULT_TEMPLATE_FILES: readonly VaultTemplateFile[] = ${JSON.stringify(files, null, 2)};
`;
  return header;
}

function main(): void {
  if (!existsSync(TEMPLATE_DIR)) {
    throw new Error(`vault-template directory not found at ${TEMPLATE_DIR}`);
  }
  const files = walkMarkdownFiles(TEMPLATE_DIR);
  if (files.length === 0) {
    throw new Error("vault-template/ has no markdown files; refusing to emit empty manifest");
  }
  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, emit(files));
  console.log(`✓ wrote ${OUT_PATH} (${files.length} files)`);
}

main();
