// SPDX-License-Identifier: Apache-2.0

// M2 smoke script — two-client WebSocket round-trip + hibernation idle check.
//
// Captures the two operator-facing M2 verification artifacts from SPEC §9:
//
//   1. Sub-500ms two-client round-trip latency (200ms target on a healthy LAN;
//      500ms is the hard gate to accommodate slow dev CPUs).
//   2. Zero `wrangler tail` output during 60+ seconds of WS idle, attesting
//      that the Hibernation API is active (ctx.acceptWebSocket) and the
//      isolate is NOT kept warm.
//
// Prerequisites:
//   - `wrangler dev` running (default: http://localhost:8788)
//   - `apps/worker/.dev.vars` present with ALLOW_LOCAL_DEV_AUTH=true
//     (the script generates a starter file at apps/worker/.dev.vars if absent)
//   - `wrangler tail --format=json` available in PATH (for hibernation check)
//
// Usage:
//   pnpm smoke:m2
//   pnpm smoke:m2 -- --base-url http://localhost:8788
//   SMOKE_EMAIL=alice@example.com pnpm smoke:m2
//
// Exits 0 on success with a summary line.
// Exits non-zero with a printed reason on any failure.

import { execFileSync, spawn } from "node:child_process";
import * as fs from "node:fs";
import * as http from "node:http";
import * as path from "node:path";
import { WebSocket } from "ws";

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const ARGS = process.argv.slice(2);
function getFlag(name: string, fallback: string): string {
  const idx = ARGS.indexOf(name);
  if (idx !== -1 && ARGS[idx + 1] !== undefined) return ARGS[idx + 1] as string;
  return fallback;
}

const BASE_URL = getFlag("--base-url", process.env.SMOKE_BASE_URL ?? "http://localhost:8788");
const WS_BASE = BASE_URL.replace(/^http/, "ws");
const DEV_EMAIL_1 = process.env.SMOKE_EMAIL_1 ?? "smoke-client1@local.test";
const DEV_EMAIL_2 = process.env.SMOKE_EMAIL_2 ?? "smoke-client2@local.test";
const SMOKE_ROOM_SLUG = process.env.SMOKE_ROOM_SLUG ?? "smoke-m2";
const SMOKE_ROOM_NAME = process.env.SMOKE_ROOM_NAME ?? "Smoke M2";
const ROUND_TRIP_LIMIT_MS = 500;
const IDLE_WINDOW_S = 60;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function fail(reason: string): never {
  console.error(`\nFAIL: ${reason}`);
  process.exit(1);
}

function log(msg: string): void {
  const ts = new Date().toISOString().slice(11, 23);
  console.log(`[${ts}] ${msg}`);
}

function devVarsPath(): string {
  // Resolve relative to repo root (this script lives in scripts/).
  const repoRoot = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
  return path.join(repoRoot, "apps", "worker", ".dev.vars");
}

function ensureDevVars(): void {
  const dvPath = devVarsPath();
  if (fs.existsSync(dvPath)) {
    console.warn(
      `[warn] ${dvPath} already exists — using it as-is. Ensure ALLOW_LOCAL_DEV_AUTH=true is set.`,
    );
    return;
  }
  const contents = [
    "# Generated by scripts/smoke-m2.ts — safe to commit to VCS? NO. See .gitignore.",
    "# Adjust values to match your environment and re-run.",
    "ALLOW_LOCAL_DEV_AUTH=true",
    'JWT_AUD=""',
    'CF_TEAM_DOMAIN=""',
    'BYOK_ENCRYPTION_KEY="dev-only-32-byte-key-change-me!!"',
    "",
  ].join("\n");
  fs.writeFileSync(dvPath, contents, { mode: 0o600 });
  console.warn(
    `[warn] Created ${dvPath} with ALLOW_LOCAL_DEV_AUTH=true. Start wrangler dev and re-run this script.`,
  );
}

// ---------------------------------------------------------------------------
// HTTP helpers (local fetch using Node http — avoids needing node-fetch)
// ---------------------------------------------------------------------------

interface ApiOk<T> {
  ok: true;
  data: T;
}
interface ApiErr {
  ok: false;
  error: { code: string; message: string };
}

async function httpGet<T>(urlPath: string, email: string): Promise<T> {
  return new Promise((resolve, reject) => {
    const url = new URL(urlPath, BASE_URL);
    const opts: http.RequestOptions = {
      hostname: url.hostname,
      port: Number(url.port) || 8788,
      path: url.pathname + url.search,
      method: "GET",
      headers: {
        Accept: "application/json",
        "X-Local-Dev-Email": email,
      },
    };
    const req = http.request(opts, (res) => {
      let body = "";
      res.on("data", (chunk: Buffer) => {
        body += chunk.toString();
      });
      res.on("end", () => {
        let parsed: unknown;
        try {
          parsed = JSON.parse(body);
        } catch {
          return reject(new Error(`non-JSON from ${urlPath}: ${body.slice(0, 200)}`));
        }
        const result = parsed as ApiOk<T> | ApiErr;
        if (result.ok === true) return resolve(result.data);
        return reject(new Error(`${urlPath} → ${result.error.code}: ${result.error.message}`));
      });
    });
    req.on("error", reject);
    req.end();
  });
}

async function httpPost<T>(urlPath: string, email: string, body: unknown): Promise<T> {
  return new Promise((resolve, reject) => {
    const url = new URL(urlPath, BASE_URL);
    const bodyStr = JSON.stringify(body);
    const opts: http.RequestOptions = {
      hostname: url.hostname,
      port: Number(url.port) || 8788,
      path: url.pathname + url.search,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Content-Length": Buffer.byteLength(bodyStr),
        Accept: "application/json",
        "X-Local-Dev-Email": email,
      },
    };
    const req = http.request(opts, (res) => {
      let buf = "";
      res.on("data", (chunk: Buffer) => {
        buf += chunk.toString();
      });
      res.on("end", () => {
        let parsed: unknown;
        try {
          parsed = JSON.parse(buf);
        } catch {
          return reject(new Error(`non-JSON from ${urlPath}: ${buf.slice(0, 200)}`));
        }
        const result = parsed as ApiOk<T> | ApiErr;
        if (result.ok === true) return resolve(result.data);
        return reject(new Error(`${urlPath} → ${result.error.code}: ${result.error.message}`));
      });
    });
    req.on("error", reject);
    req.write(bodyStr);
    req.end();
  });
}

// ---------------------------------------------------------------------------
// Step runner (mirrors smoke-live.ts for consistent output)
// ---------------------------------------------------------------------------

async function step<T>(label: string, fn: () => Promise<T>): Promise<T> {
  const startedAt = Date.now();
  try {
    const out = await fn();
    const ms = Date.now() - startedAt;
    log(`✓ [${ms.toString().padStart(5, " ")}ms] ${label}`);
    return out;
  } catch (err) {
    const ms = Date.now() - startedAt;
    log(`✗ [${ms.toString().padStart(5, " ")}ms] ${label}`);
    throw err;
  }
}

// ---------------------------------------------------------------------------
// Worker liveness check
// ---------------------------------------------------------------------------

async function assertWorkerAlive(): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    const url = new URL("/api/health", BASE_URL);
    const req = http.get(
      { hostname: url.hostname, port: Number(url.port) || 8788, path: "/api/health" },
      (res) => {
        res.resume();
        if (res.statusCode !== undefined && res.statusCode < 500) {
          resolve();
        } else {
          reject(new Error(`/api/health returned ${res.statusCode}`));
        }
      },
    );
    req.on("error", (err) => {
      reject(
        new Error(
          `Cannot reach ${BASE_URL}/api/health: ${err.message}. Is wrangler dev running? (pnpm dev)`,
        ),
      );
    });
    req.end();
  });
}

// ---------------------------------------------------------------------------
// Setup: bootstrap workspace + ensure smoke room
// ---------------------------------------------------------------------------

interface MeData {
  user: { id: string };
  workspace: { id: string };
  rooms: Array<{ id: string; slug: string; name: string }>;
}

interface RoomData {
  id: string;
  slug: string;
  name: string;
}

async function ensureRoom(email: string, workspaceId: string): Promise<RoomData> {
  // List rooms — reuse if smoke room already exists.
  const rooms = await httpGet<{ rooms: RoomData[] }>(`/api/workspaces/${workspaceId}/rooms`, email);
  const existing = rooms.rooms.find((r) => r.slug === SMOKE_ROOM_SLUG);
  if (existing !== undefined) return existing;

  // Create it.
  const created = await httpPost<{ room: RoomData }>(
    `/api/workspaces/${workspaceId}/rooms`,
    email,
    { slug: SMOKE_ROOM_SLUG, name: SMOKE_ROOM_NAME },
  );
  return created.room;
}

// ---------------------------------------------------------------------------
// WebSocket helpers
// ---------------------------------------------------------------------------

function wsUrl(roomId: string, devEmail: string): string {
  // WebSocket upgrades cannot carry custom headers in browser clients, so the
  // auth middleware accepts ?devEmail= as the local-dev bypass channel.
  const u = new URL(`/api/rooms/${roomId}/ws`, WS_BASE);
  u.searchParams.set("devEmail", devEmail);
  return u.toString();
}

function openWs(url: string): Promise<WebSocket> {
  return new Promise((resolve, reject) => {
    const ws = new WebSocket(url);
    ws.once("open", () => resolve(ws));
    ws.once("error", reject);
    // 5s connection timeout.
    const t = setTimeout(() => {
      ws.close();
      reject(new Error(`WebSocket connection to ${url} timed out after 5s`));
    }, 5000);
    ws.once("open", () => clearTimeout(t));
  });
}

function waitMessage(ws: WebSocket, timeoutMs: number): Promise<string> {
  return new Promise((resolve, reject) => {
    const t = setTimeout(() => {
      reject(new Error(`No message received within ${timeoutMs}ms`));
    }, timeoutMs);
    ws.once("message", (data) => {
      clearTimeout(t);
      resolve(data.toString());
    });
  });
}

// ---------------------------------------------------------------------------
// Round-trip test
// ---------------------------------------------------------------------------

interface WsServerMsg {
  type: string;
  payload?: {
    id?: string;
    content?: string;
    [key: string]: unknown;
  };
}

async function runRoundTripTest(roomId: string): Promise<number> {
  log(`Opening WS client 1 (${DEV_EMAIL_1}) …`);
  const ws1 = await openWs(wsUrl(roomId, DEV_EMAIL_1));
  log("WS client 1 connected.");

  log(`Opening WS client 2 (${DEV_EMAIL_2}) …`);
  const ws2 = await openWs(wsUrl(roomId, DEV_EMAIL_2));
  log("WS client 2 connected.");

  // Discard any initial "history" or "welcome" frames on both clients before
  // the round-trip test so we measure actual echo latency.
  // Strategy: send a unique sentinel from client 1 and wait until client 2
  // receives a message whose content matches. We set a 500ms overall gate.
  const sentinel = `smoke-rtt-${Date.now()}`;
  const sendPayload = JSON.stringify({
    type: "chat",
    payload: { content: sentinel },
  });

  // Drain stale messages on ws2 with a tiny window before we fire the sentinel.
  await new Promise<void>((r) => setTimeout(r, 50));

  log(`Sending sentinel from client 1: "${sentinel}"`);
  const t0 = Date.now();
  ws1.send(sendPayload);

  // Wait for ws2 to receive any message that contains our sentinel string.
  const received = await new Promise<string>((resolve, reject) => {
    const deadline = setTimeout(
      () => reject(new Error("Timed out waiting for sentinel on client 2")),
      ROUND_TRIP_LIMIT_MS + 1000, // give an extra 1s beyond the gate for a clear error
    );
    const handler = (data: Buffer | string): void => {
      const str = data.toString();
      if (str.includes(sentinel)) {
        clearTimeout(deadline);
        resolve(str);
      }
      // Otherwise keep listening — earlier frames (e.g., history replay) may
      // arrive before our echo.
    };
    ws2.on("message", handler);
  });

  const rttMs = Date.now() - t0;

  ws1.close();
  ws2.close();

  log(`Round-trip: ${rttMs}ms (gate: ${ROUND_TRIP_LIMIT_MS}ms)`);
  log(`Echo frame (truncated): ${received.slice(0, 120)}`);

  return rttMs;
}

// ---------------------------------------------------------------------------
// Hibernation / idle check via wrangler tail
// ---------------------------------------------------------------------------

async function runHibernationCheck(): Promise<void> {
  // Check wrangler is available.
  try {
    execFileSync("wrangler", ["--version"], { stdio: "ignore" });
  } catch {
    log(
      "[skip] wrangler not in PATH — skipping hibernation tail check. " +
        "Run `npx wrangler tail --format=json` manually during a 60s idle to verify.",
    );
    return;
  }

  log(`Starting wrangler tail (${IDLE_WINDOW_S}s idle window) …`);
  const tailLines: string[] = [];

  const tailProc = spawn("wrangler", ["tail", "--format=json"], {
    stdio: ["ignore", "pipe", "pipe"],
  });

  tailProc.stdout.on("data", (chunk: Buffer) => {
    // Split on newlines — wrangler tail emits one JSON object per line.
    const lines = chunk
      .toString()
      .split("\n")
      .filter((l) => l.trim().length > 0);
    for (const line of lines) {
      tailLines.push(line);
      log(`[wrangler tail] ${line.slice(0, 120)}`);
    }
  });

  tailProc.stderr.on("data", (chunk: Buffer) => {
    const msg = chunk.toString().trim();
    if (msg) log(`[wrangler tail stderr] ${msg.slice(0, 120)}`);
  });

  log(`Waiting ${IDLE_WINDOW_S}s with no activity …`);
  await new Promise<void>((r) => setTimeout(r, IDLE_WINDOW_S * 1000));

  tailProc.kill("SIGTERM");
  // Give the process a moment to flush.
  await new Promise<void>((r) => setTimeout(r, 500));

  log(`wrangler tail output lines during idle: ${tailLines.length}`);

  if (tailLines.length > 0) {
    fail(
      `Hibernation check FAILED: wrangler tail captured ${tailLines.length} line(s) during ` +
        `${IDLE_WINDOW_S}s idle. The ChatRoom DO may not be hibernating between messages. ` +
        `First line: ${tailLines[0]?.slice(0, 200)}`,
    );
  }

  log("Hibernation check PASSED: zero tail events during idle window.");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  console.log(`\nLoomwiki M2 smoke @ ${BASE_URL}`);
  console.log(`  Email 1 : ${DEV_EMAIL_1}`);
  console.log(`  Email 2 : ${DEV_EMAIL_2}`);
  console.log(`  Room    : ${SMOKE_ROOM_SLUG}`);
  console.log(`  RTT gate: ${ROUND_TRIP_LIMIT_MS}ms`);
  console.log(`  Idle    : ${IDLE_WINDOW_S}s`);
  console.log("");

  // 1. Generate .dev.vars if absent (warns if present).
  ensureDevVars();

  // 2. Confirm wrangler dev is alive.
  await step("worker liveness check", assertWorkerAlive);

  // 3. Bootstrap user 1 + workspace + smoke room.
  const me1 = await step("/api/me (client 1)", () => httpGet<MeData>("/api/me", DEV_EMAIL_1));
  log(`  user.id        = ${me1.user.id}`);
  log(`  workspace.id   = ${me1.workspace.id}`);

  // Bootstrap user 2 so the room-member check passes for ws2.
  const me2 = await step("/api/me (client 2)", () => httpGet<MeData>("/api/me", DEV_EMAIL_2));
  log(`  user2.id       = ${me2.user.id}`);

  const room = await step(`ensure room "${SMOKE_ROOM_SLUG}"`, () =>
    ensureRoom(DEV_EMAIL_1, me1.workspace.id),
  );
  log(`  room.id        = ${room.id}`);

  // 4. Round-trip test.
  const rttMs = await step("WS round-trip (two clients)", () => runRoundTripTest(room.id));

  if (rttMs > ROUND_TRIP_LIMIT_MS) {
    fail(
      `Round-trip latency ${rttMs}ms exceeds ${ROUND_TRIP_LIMIT_MS}ms gate. Check wrangler dev CPU / D1 local performance.`,
    );
  }

  // 5. Hibernation idle check.
  await step(`hibernation idle check (${IDLE_WINDOW_S}s)`, runHibernationCheck);

  console.log(
    `\nSmoke M2 PASSED. Round-trip: ${rttMs}ms (gate ${ROUND_TRIP_LIMIT_MS}ms). ` +
      `Hibernation: zero tail events in ${IDLE_WINDOW_S}s idle.`,
  );
}

main().catch((err) => {
  console.error("\nSmoke M2 failed:", err instanceof Error ? err.message : String(err));
  process.exit(1);
});
